language: ruby
cache:
  bundler: true
  apt: true
  directories:
  - node_modules
  - bower_components
before_install: nvm install v$(< .node-version)
install: rake deps
deploy:
  provider: script
  skip_cleanup: true
  script: "rvm $(< .ruby-version) do bundle exec rake deploy"
  on:
    branch: master
