# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a74335461e316aeabed0bc2b1dbc1aa85ade60eaa02d40dabfd0ff047c7a995af6c76295c7c815307659ea30c9c330cc817cf3a33050f3ff51b3801331d82664

test:
  secret_key_base: f320b938872f265c8758f6950a869f1da9be8ff8005214700835821bc1d36aba3a3d03e27bf4d3b21752d6017c4494dd7d98d9cc72eebc6412fc79f769e74d79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
